# Generated by Django 4.2.7 on 2026-03-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=0.0)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_open_now', models.BooleanField(default=True)),
                ('fuel_types', models.JSONField(default=list)),
            ],
        ),
    ]
