# Generated by Django 6.0.3 on 2026-03-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stations/'),
        ),
        migrations.AddField(
            model_name='station',
            name='open_time',
            field=models.CharField(blank=True, help_text='e.g. 08:00 - 22:00 or 24/7', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='fuel_types',
            field=models.JSONField(default=list, help_text='List of strings, e.g. ["PETROL AI-95", "CNG"]'),
        ),
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude (Y)'),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude (X)'),
        ),
    ]
