# Generated by Django 6.0.3 on 2026-03-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_description_station_image_station_open_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. AI-91, AI-95, CNG', max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='station',
            name='fuel_types',
        ),
        migrations.AddField(
            model_name='station',
            name='fuels',
            field=models.ManyToManyField(blank=True, related_name='stations', to='stations.fueltype'),
        ),
    ]
