# Generated by Django 4.2.7 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0004_swap_station_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="has_coffee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="station",
            name="has_fast_food",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="station",
            name="has_shop",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="station",
            name="has_wifi",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="station",
            name="image_url",
            field=models.URLField(blank=True, help_text="Optional direct internet URL for station image", null=True),
        ),
    ]
