# Generated by Django 6.0.4 on 2026-06-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_station_extra_services_and_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='phone',
            field=models.CharField(blank=True, help_text='e.g. +998901234567', max_length=50, null=True),
        ),
    ]
